"""add column for security key credentials

Revision ID: 3b37a75d0aab
Revises: 7cb5548a32b9
Create Date: 2021-04-24 16:54:27.105962

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b37a75d0aab"
down_revision = "7cb5548a32b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dashboard_users",
        sa.Column(
            "webauthn_credentials", postgresql.ARRAY(sa.Binary()), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dashboard_users", "webauthn_credentials")
    # ### end Alembic commands ###
