"""init user table

Revision ID: 7cb5548a32b9
Revises:
Create Date: 2021-04-11 20:43:17.746516

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7cb5548a32b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_users",
        sa.Column("user_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("user_password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_uuid"),
        sa.UniqueConstraint("user_email"),
        sa.UniqueConstraint("user_password_hash"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboard_users")
    # ### end Alembic commands ###
